### ISSUE TITLE
Tracking of Python 3.11 compatibility

### ISSUE THREAD

**Issue by C4ptainCrunch** [ics-py/ics-py#337]
Python 3.11 tests are failing since a few hours, this is due to a legit bug in Python and is tracked on https://github.com/pytest-dev/pytest/issues/10008 and https://github.com/python/cpython/pull/93359. This should be fixed with the next pre-release of Python.

This issue also keep track of the stable release that is currently targeted for 2022-10-03. At that time, we should:

- [x] Change the build matrix to disallow 3.11 tests to fail
- [x] Enforce 3.11 tests in the branch protection
- [ ] Add 3.12 in the tests (as experimental) ?
- [x] Update PyPi classifiers
- [x] Build with 3.11 on ReadThe Docs ([.readthedocs.yaml](https://github.com/ics-py/ics-py/blob/main/.readthedocs.yaml#L9))
- [x] Build tox targets `docs` and `checks` on 3.11

Edit:

- [ ] check PyPy for [new releases](https://doc.pypy.org/en/latest/index-of-release-notes.html#combined-releases)
- [x] update mypy target [python_version](https://github.com/ics-py/ics-py/blob/acebb18ed73a3d865bfb2e1abb4409e5fde3356b/tox.ini#L99) 
- [ ] update the [pinned version of mypy](https://github.com/ics-py/ics-py/blob/acebb18ed73a3d865bfb2e1abb4409e5fde3356b/tox.ini#L27) and check for new breakages
  (we should do that semi-regularly and this might actually be a good point in time for that, see also #329)

**Comment by N-Coder** [comment]
We might also want to include these steps in general as a "Updating for a newly-released python version" section in the docs. As a refence we can also take the changes made in #301. I'd also include:
- check PyPy for [new releases](https://doc.pypy.org/en/latest/index-of-release-notes.html#combined-releases)
- update mypy target [python_version](https://github.com/ics-py/ics-py/blob/acebb18ed73a3d865bfb2e1abb4409e5fde3356b/tox.ini#L99) 
- update the [pinned version of mypy](https://github.com/ics-py/ics-py/blob/acebb18ed73a3d865bfb2e1abb4409e5fde3356b/tox.ini#L27) and check for new breakages
  (we should do that semi-regularly and this might actually be a good point in time for that, see also #329)

**Comment by N-Coder** [comment]
And also for deprecating old versions:
- update pyproject.toml and tox.ini
- update `--py37-plus` for pyupgrade in .pre-commit-config.yaml
- check for compatibility imports, e.g. cached_property, stuff from typing, importlib_resources,...

**Comment by C4ptainCrunch** [comment]
Update: we are almost there. We are only missing 3.12 experimental tests and maybe PyPy and mypy (but that can be done later)
I'm also considering releasing 0.8.0dev1 with the changes
